[package]
name = "graviplex-engine"
version = "0.2.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
ultraviolet = { workspace = true }
pollster = { workspace = true }
log = { workspace = true }
