[package]
name = "graviplex"
version = "0.2.0"
edition = "2021"

[dependencies]
graviplex-engine = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
egui = { workspace = true }
egui-winit = { workspace = true }
ultraviolet = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
pollster = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
